on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build && npm ci --prod

      - name: Zip dist folder contents
        run: zip -qq -j ./bundle.zip ./dist/* && zip -qq -r ./bundle.zip ./node_modules/

      - name: Deploy zip to aws lambda
        if: github.ref == 'refs/heads/master'
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: ${{ github.event.repository.name }}
          zip_file: ./bundle.zip
